import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import "antd/dist/reset.css";
import "./styles/main.css";
import "./styles/responsive.css";
import Header from "../components/layout/Header";
import FloatingButton from "../components/ui/FloatingButton";
import AnimatedFooter from "../components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "نرتقي | لوحة التحكم",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body
        dir="rtl"
        className={`min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50 to-teal-100 relative  ${geistSans.variable} ${geistMono.variable}`}
      >

        {children}
      </body>
    </html>
  );
}
